# -*- coding: utf-8 -*-
"""module8_metrics-scikit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCiU-Wgh7nftvBSQyqF4eukXuXAyxTQM
"""

import numpy as np
from sklearn.metrics import precision_score, recall_score

def main():
    N = int(input("Enter N: "))
    data = []
    for i in range(N):
        x = int(input("Enter true label X" + str(i+1) + " (0 or 1): "))
        y = int(input("Enter predicted label Y" + str(i+1) + " (0 or 1): "))
        data.append((x, y))
    data = np.array(data, dtype=int)
    xs = data[:, 0]
    ys = data[:, 1]
    precision = precision_score(xs, ys, zero_division=0)
    recall = recall_score(xs, ys, zero_division=0)
    print("Precision:", precision)
    print("Recall:", recall)

if __name__ == "__main__":
    main()